export const reducerCases = {
    SET_TOKEN: "SET_TOKEN",
    SET_PLAYLIST: "SET_PLAYLIST", //Sidebar
    SET_USER: "SET_USER",
    SET_PLAYLIST_BODY: "SET_PLAYLIST_BODY",
    SET_PLAYING: "SET_PLAYING",
};